"""recipes table

Revision ID: 09d60f84aecf
Revises: b4cbf62dc4e2
Create Date: 2018-05-17 13:12:50.747349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d60f84aecf'
down_revision = 'b4cbf62dc4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('recipe_category', sa.Integer(), nullable=True))
    op.create_foreign_key('category', 'recipe', 'recipe_category', ['recipe_category'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category', 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'recipe_category')
    # ### end Alembic commands ###
