"""recipes table

Revision ID: af69acf0c267
Revises: 1de44cf1afbd
Create Date: 2018-10-14 03:35:31.885697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af69acf0c267'
down_revision = '1de44cf1afbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipename', sa.String(length=140), nullable=True),
    sa.Column('ingredients', sa.String(length=140), nullable=True),
    sa.Column('method', sa.String(length=140), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_category'), 'recipe', ['category'], unique=False)
    op.create_index(op.f('ix_recipe_recipename'), 'recipe', ['recipename'], unique=False)
    op.create_index(op.f('ix_recipe_timestamp'), 'recipe', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_timestamp'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_recipename'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_category'), table_name='recipe')
    op.drop_table('recipe')
    # ### end Alembic commands ###
