"""empty message

Revision ID: b4a79a5203c8
Revises: af69acf0c267
Create Date: 2018-10-14 06:48:29.775632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a79a5203c8'
down_revision = 'af69acf0c267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('description', sa.String(length=140), nullable=True))
    op.drop_index('ix_user_firstname', table_name='user')
    op.create_index(op.f('ix_user_firstname'), 'user', ['firstname'], unique=False)
    op.drop_index('ix_user_lastname', table_name='user')
    op.create_index(op.f('ix_user_lastname'), 'user', ['lastname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_lastname'), table_name='user')
    op.create_index('ix_user_lastname', 'user', ['lastname'], unique=1)
    op.drop_index(op.f('ix_user_firstname'), table_name='user')
    op.create_index('ix_user_firstname', 'user', ['firstname'], unique=1)
    op.drop_column('recipe', 'description')
    # ### end Alembic commands ###
