"""recipes table

Revision ID: b4cbf62dc4e2
Revises: 2d17e0915285
Create Date: 2018-05-17 12:48:13.265196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4cbf62dc4e2'
down_revision = '2d17e0915285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipename', sa.String(length=140), nullable=True),
    sa.Column('ingredients', sa.String(length=140), nullable=True),
    sa.Column('method', sa.String(length=140), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category'],['recipe_category.id'],),
    sa.PrimaryKeyConstraint('id'),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_timestamp'), 'recipe', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_timestamp'), table_name='recipe')
    op.drop_table('recipe')
    # ### end Alembic commands ###
